[tools]
lefthook = "2.1.9"

# lefthook hooks
actionlint = "1.7.12"
"github:betterleaks/betterleaks" = "1.5.0"
node = "24.16.0"
pinact = "4.0.0"
"github:fohte/basefmt" = "0.1.0"
shellcheck = "0.11.0"
shfmt = "3.13.1"
