version: 2
snapshot:
  widths:
    - 375 # Mobile
    - 768 # Tablet
    - 1280 # Desktop
  minHeight: 1024
  enableJavaScript: true
  waitForTimeout: 30000
  waitForSelector: body
static:
  baseUrl: /
  cleanUrls: true
  include: '**/*.html'
  exclude:
    - '**/404.html'
discovery:
  allowedHostnames: []
  networkIdleTimeout: 100
  disableCache: false
