repos:
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.0.3
    hooks:
      - id: editorconfig-checker
  - repo: local
    hooks:
      - id: bun-format
        name: bun format
        entry: bun run format
        language: system
        pass_filenames: false
