#!/usr/bin/env bash

set -euo pipefail

# Get URL from: Get share links -> Share Link
# e.g. https://imgur.com/a/abcdefg
imgur_url="$1"

imgur_id="$(echo "$imgur_url" | rev | cut -d'/' -f1 | rev)"

curl -s \
  -H "Authorization: Client-ID $IMGUR_CLIENT_ID" \
  https://api.imgur.com/3/image/"$imgur_id" |
  jq -r '.data | [.id, .width, .height] | @tsv' |
  while IFS=$'\t' read -r id width height; do
    cat << EOF
<ImgurImage
  id="${id}"
  alt=""
  caption=""
  width={${width}}
  height={${height}}
/>
EOF
  done
