issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fohte@11088009/fohte.net@268038795:ref:refs/heads/(main|master)$
claim_pattern:
  job_workflow_ref: ^fohte/fohte.net/\.github/workflows/boilerplate-update\.yml@[^@]+$
permissions:
  contents: write
  pull_requests: write
  workflows: write
