name: Percy Visual Testing

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  percy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          install: true

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            ~/.bun/install/global
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
            ${{ runner.os }}-bun-

      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
            .contentlayer
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package.json', '**/bun.lockb') }}-${{ hashFiles('src/**', 'public/**', 'contents/**') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package.json', '**/bun.lockb') }}-
            ${{ runner.os }}-nextjs-

      - run: bun install --frozen-lockfile

      - name: Build site
        run: bun run build

      - name: Run Percy snapshots
        run: bun run percy
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
