name: Reviewdog

on:
  pull_request:

jobs:
  reviewdog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: reviewdog/action-setup@v1
      - run: bun install --frozen-lockfile

      - run: |
          result="$(bun run textlint 'contents/**/*.mdx' -f checkstyle || true)"
          echo "$result" | reviewdog -f=checkstyle -name="textlint" -reporter='github-pr-check'
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
