name: Reviewdog

on:
  pull_request:

jobs:
  reviewdog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup mise
        uses: jdx/mise-action@v3
        with:
          install: true
      - uses: reviewdog/action-setup@v1

      - run: corepack enable

      - name: Get pnpm store directory
        id: pnpm-store
        run: echo "path=$(pnpm store path)" >> "$GITHUB_OUTPUT"

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.pnpm-store.outputs.path }}
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
            ${{ runner.os }}-pnpm-

      - run: pnpm install --frozen-lockfile

      - run: |
          result="$(pnpm exec textlint 'contents/**/*.mdx' -f checkstyle || true)"
          echo "$result" | reviewdog -f=checkstyle -name="textlint" -reporter='github-pr-check'
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
