name: Reviewdog

on:
  pull_request:

jobs:
  reviewdog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          install: true
      - uses: reviewdog/action-setup@v1

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            ~/.bun/install/global
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
            ${{ runner.os }}-bun-

      - run: bun install --frozen-lockfile

      - run: |
          result="$(bun run textlint 'contents/**/*.mdx' -f checkstyle || true)"
          echo "$result" | reviewdog -f=checkstyle -name="textlint" -reporter='github-pr-check'
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
