name: Reviewdog

on:
  pull_request:

jobs:
  reviewdog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        cache: yarn
      - uses: reviewdog/action-setup@v1
      - run: yarn install --frozen-lockfile

      - run: |
          yarn run textlint 'contents/**/*.mdx' -f checkstyle |
            reviewdog -f=checkstyle -reporter=github-pr-review
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
