name: VRT approval

on:
  pull_request:
    types: [synchronize, labeled]

jobs:
  vrt-approval:
    permissions:
      contents: read
      pull-requests: write
      statuses: write
    uses: fohte/storybook-vrt-workflows/.github/workflows/vrt-approval.yml@691148d6e8e53b86c8f93b5b54cadbd8308b06d3 # v0.1.6
    with:
      r2-bucket: fohte-net-vrt
