name: Visual Regression Testing

on:
  pull_request:
    branches: [master]
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'next.config.js'
      - 'contentlayer.config.ts'

jobs:
  vrt:
    name: Visual Regression Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build application
        run: bun run build

      - name: Start application
        run: |
          bun run start &
          sleep 10
          curl -f http://localhost:3000 || exit 1
        env:
          NODE_ENV: production

      - name: Capture screenshots
        run: bun run vrt:capture
        env:
          VRT_BASE_URL: http://localhost:3000

      - name: Run visual regression test
        run: bun run vrt:run
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Comment PR with VRT results
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            try {
              const reportPath = path.join('.reg', 'index.html');
              if (fs.existsSync(reportPath)) {
                const reportUrl = process.env.VRT_REPORT_URL || 'Check the VRT report in the job logs';
                await github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: `## 📸 Visual Regression Test Results\n\n${reportUrl}`
                });
              }
            } catch (error) {
              console.log('Could not post VRT results comment:', error);
            }
